name: Deploy Async Handler Middleware Microservice

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Build Docker image
        run: docker build -t async-handler-microservice .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag async-handler-microservice mydockerhub/async-handler-microservice
          docker push mydockerhub/async-handler-microservice

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
            docker pull mydockerhub/async-handler-microservice
            docker stop async-handler-container || true
            docker rm async-handler-container || true
            docker run -d --name async-handler-container -p 3003:3003 mydockerhub/async-handler-microservice
          EOF
